version: '3.8'
services:
  jobboo-app:
    image: akidev9777/jobboo
    container_name: jobboo
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql-container:
        condition: service_healthy
    networks:
      - jobboo

  mysql-container:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: myappdb
    networks:
      - jobboo
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10

networks:
  jobboo:
    driver: bridge
