apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  HOST: am9iYm9vLWRiLW15c3FsLXN2Yw==          # base64로 인코딩된 jobboo-db-mysql-svc
  PORT: MzMwNg==                     # base64로 인코딩된 3306
  DATABASE: bXlhcHBkYg==             # base64로 인코딩된 myappdb
  USERNAME: cm9vdA==                 # base64로 인코딩된 root
  PASSWORD: MTExMQ==                 # base64로 인코딩된 1111