name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

env:
  DOCKER_IMAGE: akidev9777/jobboo
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  TARGET_REPOSITORY: rednine9777/jobboo-helm
  VALUES_FILE: jobboo-values.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Build the Java project with Maven
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      # 4. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      # 5. Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ env.DOCKER_IMAGE }}:${{ github.sha }} .

      # 6. Push Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      # 7. Clone the TARGET_REPOSITORY
      - name: Clone Helm Chart Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPOSITORY }}
          token: ${{ env.GIT_TOKEN }}
          path: helm-chart

      # 8. Update image tag in values.yaml
      - name: Update Image Tag in values.yaml
        run: |
          sed -i 's/tag: ".*"/tag: "'${{ github.sha }}'"/' helm-chart/${{ env.VALUES_FILE }}

      # 9. Commit and Push Changes
      - name: Commit and Push Changes
        working-directory: helm-chart
        env:
          GIT_TOKEN: ${{ env.GIT_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add ${{ env.VALUES_FILE }}
          git commit -m "Update image tag to ${{ github.sha }}"
          git push https://oauth2:${GIT_TOKEN}@github.com/${{ env.TARGET_REPOSITORY }}.git
